const jokes_obj= {"lamejokes":["why was the math teacher late to work? she took the rhombus.",
    "i'm really excited for the next autopsy club. it's open mike night!",
    "where do spiders seek health advice? webmd.",
    "what did yoda say when he saw himself in 4k? hdmi",
    "my daughter thinks i don't give her enough privacy. at least that's what she wrote in her diary.",
    "a friend of mine got into photographing salmon in different clothing. he said he liked shooting fish in apparel.",
    "why can't you trust an atom? because they make up everything.",
    "i'd like to go to holland someday. wooden shoe?",
    "the guy that invented the umbrella was gonna call it the brella. but he hesitated.",
    "fun fact: australia's biggest export is boomerangs. it's also their biggest import.",
    "what kind of car runs on leaves? an autumn-mobile!",
    "i tried to organize a professional hide-and-seek tournament, but it was a complete failure. good players are hard to find.",
    "before the invention of the wheel… everything was a drag!",
    "what do you call it when dwayne johnson buys a cutting tool? rock pay-for scissors.",
    "what do you call a hippie's wife? a mississippi!",
    "what did the duck say when she bought a lipstick? put it on my bill!",
    "what do you call a man with a rubber toe? roberto!",
    "what do you give to a sick lemon? lemon aid!",
    "what did the little mountain say to the bigger mountain? hi cliff!",
    "why are there gates around cemeteries? because people are dying to get in!",
    "what do you call a cow with two legs? lean beef!",
    "what do bees do if they need a ride? wait at the buzz stop!",
    "what do you call a monkey that loves doritos? a chipmunk!",
    "why did the can crusher quit his job? because it was soda pressing!",
    "do you remember that joke i told you about my spine? it was about a weak back!",
    "i just went to an emotional wedding. even the cake was in tiers.",
    "when's the best time to go to the dentist? tooth-hurtie!",
    "why do seagulls fly over the sea? because if they flew over the bay, they're bagels!",
    "what do you call a farm that makes bad jokes? corny!",
    "why do fish live in salt water? because pepper makes them sneeze!",
    "what kind of streets do ghosts haunt? dead ends!",
    "what do you tell actors to break a leg? because every play has a cast!",
    "what kind of dogs love car racing? lap dogs!",
    "what did winnie the pooh say to his agent? show me the honey!",
    "what do you call birds who stick together? vel-crows.",
    "today i gave my dead batteries away. they were free of charge.",
    "what do you call it when one cow spies on another? a steak out!",
    "what happens when a frog's car breaks down? it gets toad!",
    "what's the best thing about switzerland? i don't know, but its flag is a big plus!",
    "my favorite word is drool. it just rolls off the tongue.",
    "why is peter pan always flying? he neverlands.",
    "i just wrote a book on reverse psychology. do not read it.",
    "what does a zombie vegetarian eat? graaaaaaaains!",
    "my new thesaurus is terrible. not only that, it's also terrible.",
    "what did the blanket say as it fell off the bed? oh sheet!",
    "why do cow-milking stools only have three legs? 'cause the cow's got the udder!",
    "how did darth vader know what luke got him for christmas? he felt his presents.",
    "what's the last thing that goes through a bug's mind when it hits a windshield? its butt.",
    "what did the janitor say when he jumped out of the closet? supplies!",
    "imagine if americans switched from pounds to kilograms overnight. there would be mass confusion!",
    "what did batman say to robin before they got in the car? robin, get in the car.",
    "i have an addiction to cheddar cheese. but it's only mild.",
    "why shouldn't you write with a broken pencil? because it's pointless!",
    "why did the scarecrow win an award? he was outstanding in his field.",
    "what did the buffalo say when his son left? bison!",
    "i was sitting in traffic the other day.  probably why i got run over.",
    "what's red and shaped like a bucket? a blue bucket painted red.",
    "what don't ants get sick? they have anty-bodies.",
    "what do you call a fish with no eye? fsh.",
    "why do you smear peanut butter on the road? to go with the traffic jam.",
    "when is your door not actually a door? when it's ajar.",
    "what's green, fuzzy, and would hurt if it fell on you out of a tree? a pool table.",
    "a communist joke isn't funny unless everyone gets it.",
    "what did one dish say to the other? dinner is on me!",
    "what does a house wear? address!",
    "why can't you hear a pterodactyl go to the bathroom? because the pee is silent.",
    "cosmetic surgery used to be such a taboo subject. now you can talk about botox and nobody raises an eyebrow.",
    "what do you call someone who immigrated to sweden? artificial swedener.",
    "have you heard the one about the corduroy pillow? it's making headlines.",
    "what's the dumbest animal in the jungle? a polar bear!",
    "i'm thinking about removing my spine. i feel like it's only holding me back.",
    "did you hear about the two thieves who stole a calendar? they each got six months.",
    "i'm terrified of elevators so i'm going to start taking steps to avoid them.",
    "have you heard of the band 923 megabytes? probably not, they haven't had a gig yet.",
    "where do mansplainers get their water? from a well, actually.",
"why are social media influencers afraid when they go to the woods alone at night? they're constantly being followed.",
"i will never understand why manslaughter is illegal. men should be able to laugh at whatever they want.",
"what did the green grape say to the purple grape? breathe, damn it! breathe!",
"i put my root beer into a square glass. now it's just beer.",
"they told me a mask was enough to get into the supermarket. they lied, everybody else was also wearing pants.",
"not to brag, but i defeated our local chess champion in less than five moves. finally my high school karate lessons came to some use.",
"i hate russian dolls. they're so full of themselves.",
"i went on a once-in-a-lifetime vacation. never again.",
"my grandfather has the heart of a lion and a lifetime ban from the national zoo.",
"what's green and has wheels? grass. i lied about the wheels.",
"sometimes i tuck my knees into my chest and lean forward. that's just how i roll.",
"i like to spend every day as if it's my last. staying in bed and calling for a nurse to bring me more pudding.",
"i got fired from my job at the bank today. an old lady came in and asked me to check her balance, so i pushed her over.",
"i wasn't going to visit my family this december, but my mom promised to make me eggs benedict. so i'm going home for the hollandaise.",
"my dad's answer to everything is alcohol. he doesn't drink, it's just that he's really bad at crossword puzzles.",
"where did the computer go dancing? the disc-o!",
"what do you call a dangerous sun shower? a rain of terror!",
"i used to hate facial hair but then it grew on me.",
"what's the difference between a dirty bus stop and a lobster with breast implants? one is a crusty bus station and the other is a busty crustacean.",
"how many tickles does it take to make an octopus laugh? ten tickles.",
"i used to be addicted to the hokey pokey but then i turned myself around.",
"why didn't the astronaut come home to his wife? he needed his space.",
"what's the most terrifying word in nuclear physics? oops!",
"i watched hockey before it was cool. they were basically swimming.",
"there's no hole in your shoe? then how'd you get your foot in it?",
"a cowherd counted 48 cows on his property. but when he rounded them up, he had 50.",
"when the two rabbit ears got married, it was a nice ceremony. but the reception was amazing.",
"why couldn't the bicycle stand up? because it was too tired.",
"a chicken coup only has two doors. if it had four, it would be a chicken sedan.",
"three fish are in a tank. one asks the others, how do you drive this thing?",
"why don't crabs donate? because they're shellfish.",
"what did blackbeard the pirate say when he turned eighty? aye, matey.",
"how does your feline shop? by reading a catalogue.",
"it's hard to teach kleptomaniacs humor. they take things so literally.",
"sunny-side up, scrambled, or an omelet? it doesn't matter. they're all eggcellent.",
"don't worry if you miss a gym session. everything will work out.",
"ever tried to eat a clock? it's time-consuming.",
"who can jump higher than a house? pretty much anyone.",
"what do an apple and an orange have in common? neither one can drive.",
"why did the businessman invest in smith & wollensky? he wanted to stake his claim.",
"five guys walk into a bar. you think one of them would've seen it.",
"this sweet ride has four wheels and flies. it's a garbage truck.",
"how many bugs do you need to rent out an apartment? ten-ants.",
"i want to go camping every year. that trip was so in tents.",
"wait, you don't want to hear a joke about potassium? k.",
"how do you organize a space-themed hurrah? you planet.",
"your ex. that's the punchline.",
"how do you feel when there's no coffee?  depresso.",
"i broke my arm in two places. you know what the doctor told me? stay out of those places!",
"what do you give a sick bird? tweetment.",
"where did the king keep his armies? up his sleevies.",
"what are the biggest enemies of caterpillars? dogerpillers.",
"what do you call an empty can of cheese whiz? cheese was.",
"what did mario say when he broke up with princess peach? it's not you, it's a-me!",
"what's the award for being best dentist? a little plaque.",
"what did the finger say to the thumb? i'm in glove with you.",
"what do you call a magician dog? a labracadabrador.",
"what concert costs only 45 cents? 50 cent and nickelback.",
"what do sprinters eat before a race? nothing, they fast.",
"who invented the round table? sir cumference.",
"what do you call the security guards outside of samsung? the guardians of the galaxy.",
"there are three types of people in the world. those of us who are good at math and those of us who aren't.",
"what sound does a nut make when it sneezes? cashew!",
"why do ghosts love elevators? because it lifts their spirits.",
"what's the best way to carve wood? whittle by whittle.",
"why was the snowman looking through a bag of carrots? he was picking his nose.",
"what do you call a belt made out of watches? a waist of time.",
"how can you make seven an even number? just take away the 's'!",
"what did the lawyer wear to court? a lawsuit!",
"what do you call hijklmno? h20!",
"how do you find will smith in the snow? just follow the fresh prints!",
"what did the clock do when it was hungry? it went back four seconds.",
"what do you call a dog with no legs? you can call him whatever you want, he's still not coming.",
"i still remember the last thing my grandfather said before kicking the bucket: hey, you want to see how far i can kick this bucket?"]}

export default jokes_obj;