const riddle_obj = {
    "map":"i have lakes but no water, mountains but no stone and cities but no buildings. what am i? ",
    "fire":"i am always hungry and will die if not fed, but whatever i touch will soon turn red. what am i? ",
    "feather":"i am easy to lift but hard to throw. what am i? ",
    "door knock or doorbell":"i get answered even though i never ask a question. what am i? ",
    "breath":"i’m light as a feather, yet the strongest man can’t hold me for five minutes. what am i? ",
    "cloud":"i do not have wings, but i can fly. i don’t have eyes, but i will cry! what am i? ",
    "carpet":"i am bought by the yard but worn by the foot. what am i? ",
    "battery":"i have no life, but i can die. what am i? ",
    "street":"i go around all the places, cities, towns, and villages, but never come inside. what am i? ",
    "tomorrow":"i will always come and never arrive today. what am i? ",
    "umbrella":"when the water comes down, when it rains, i go up. what am i? ",
    "key":"i turn once, what is out will not get in. i turn again, what is in will not get out. what am i? ",
    "echo":"i speak without a mouth and hear without ears. i have no body but come alive with wind. what am i? ",
    "towel":"i am wet when drying. what am i? ",
    "light":"i can fill a room, but i take up no space. what am i? ",
    "your nose":"i run, yet i have no legs. what am i? ",
    "bubble":"no matter what, i come to you round, floating up, floating down. a single pop, i’m on the ground. then comes your unpleasant frown. what am i? ",
    "the dictionary":"i am the only place in the world where today comes before yesterday. what am i? ",
    "crane":"i have a long neck, am the name of a bird. i am on cargo of ships. i eat but am not alive. what am i? ",
    "plate":"i am always on the dinner table, but you don’t get to eat me. what am i? ",
    "your shadow":"i am often following you and copying your every move, yet you can never touch me or catch me. what am i? ",
    "stapler":"with pointed fangs i sit and wait; with piercing force i crunch out fate; grabbing victims, proclaiming might; physically joining with a single bite. what am i? ",
    "the moon":"people have stepped on me, but not many. i never stay full for long. i have a dark side. what am i? ",
    "the refrigerator":"i am always running, but never get tired or hot. what am i? ",
    "guitar":"i have a head much smaller than my long neck. people who play with me pick at me and that’s fine. what am i? ",
    "handsome":"if you take away one hand, some will remain. what am i? ",
    "bridge":"you can play me with cards, but don’t burn me, rest glasses on me or walk across me. what am i? ",
    "castle":"halo of water, tongue of wood, walls of stone, long have i stood. what am i? ",
    "money":"people make me, save me, change me, raise me. what am i? ",
    "temper":"the shorter i am, the bigger i am. what am i? ",
    "popcorn":"i make a loud sound when i’m changing. when i do change, i get bigger, but i weigh less. what am i? ",
    "your heart":"it can be said: to be gold is to be good; to be stone is to be nothing; to be glass is to be fragile; to be cold is to be cruel. what am i? ",
    "keyboard":"i have keys, but no locks. i have space, but no room. you can enter, but can’t go inside. what am i? ",
    "lettuce":"i am the only vegetable that is never sold frozen, canned, processed, cooked, or in any other form but fresh. what am i? ",
    "cat":"my first is in chocolate, but not in ham. my second is in cake and also in jam. my third at tea-time is easily found. my whole is a friend who’s often around. what am i? ",
    "onion":"i add lots of flavor and have many layers, but if you get too close, i’ll make you cry. what am i? ",
    "brain":"i don’t have eyes, ears, nose, and tongue, but i can see, smell, hear, and taste everything. what am i? ",
    "wheat, heat, eat, tea":"i am a word of five letters and people eat me. if you remove the first letter, i become a form of energy. remove the first two and i’m needed to live. scramble the last three and you can drink me. what am i? ",
    "squash":"my name seems harsh, but i am still and silent. you are supposed to eat me, but some display me. my name is not easy to do to me because i am hard on the outside. what am i? ",
    "Brain":"it’s good to stretch me and push my limits. the more you use me, the stronger i get. when i am sharp, i’m at my best. what am i? ",
    "water":"i run, but i don’t walk. i drip and drop, but i can’t pick myself up. you have to consume me and sometimes i surround you. what am i? ",
    "blade of grass":"i sound like i could cut you, but i’m actually quite comfortable. i can be green or yellow. i can be stiff or soft. i am a friend to bugs and also bare feet. what am i? ",
    "wine glass":"i have a stem, but i am not a flower. i have a foot, but i cannot hop. children are too young to hold me. what am i? ",
    "smile":"i can be open or closed, or big or small. i can reveal the truth or hide it. i am almost always welcome and can spring up unannounced. everyone has one, but not everyone shares. laughter comes after me. what am i? ",
    "ball of yarn":"i am round as a sphere, but then you make me something else. i am one hundred yards long, or even longer. what am i? ",
    "mirror":"you can touch me, but i can’t touch you back. you can see me, but i only reflect you and can never reject you. what am i? ",
    "sneeze":"i can travel at nearly 100 miles per hour, but never leave the room. you can cover me up, but that doesn’t slow me down. you will not know if i come only once or again and again and again. what am i? ",
    "footsteps":"many times, you need me. the more and more you take me further, the more and more you leave me behind. what am i? ",
    "coffin":"the one who makes me does not need me, when he makes me. the one who buys me does not use me for himself or herself. the one who uses me doesn’t know that he or she is using me. what am i? ",
    "the mouth of a river":"i don’t have money, though i do have banks. i feed others, though i don’t eat. cross me if you can, i won’t be mad. what am i? ",
    "empty":"take away my first letter, and i still sound the same. take away my last letter, i still sound the same. even take away my letter in the middle, i will still sound the same. i am a five-letter word. what am i? ",
    "egg":"i have no bones and no legs, but if you keep me warm, i will soon walk away. what am i? ",
    "hemlock":"half of me will mend, the other half will imprison. when i am together, i will poison. who am i? ",
    "cannibals":"our dinner guests cry that we are evil, when they notice their place in the meal. but it’s no big deal. we are just one big happy tribe that gets real fed up with people! who are we? ",
    "he is a minister.":"man who lives in new york legally married three women. he did not get a divorce, an annulment, or legally separate. who is he? ",
    "lifeguard":"my first four letters describe all living things. my last five letters are another word for knight. my job is to save you, and i’m a fan of water. who am i? ",
    "dentist":"i craft crowns of gold and bridges of silver. who am i? ",
    "mailman":"i carry a lot of secrets, happy or sad. i drive or walk to my destination rain or shine to make sure i give you what is truly yours. everything that i bring with me is destined for only for one place which is decided in advance. who am i? ",
    "waiter / waitress":"i can help a minor, i can help a senior. i can take care of you, and no matter what your mood is, i always give you a happy face. i probably won’t give you any advice, but i am always grateful when you give me tips. who am i? ",
    "barber":"i wash, cut, and shave a dozen times a day yet i still have lots of hair. who am i? ",
    "police officer":"sometimes you are relieved to see me, and other times you run from me in fear. sometimes i stop you and sometimes i let you go, but whenever you need me, i am always a quick call away. who am i? ",
    "cupid":"i am small, have wings, and carry a weapon. i target people and once i do, they’re usually glad i did. february is the month in which i appear the most. who am i? ",
    "the tooth fairy":"i have wings and a wand. when you lose something and leave it under your pillow, i leave you a prize. who am i? ",
    "tarzan":"i grew up outside society. i am wild, my voice echoes throughout the jungle, and nature is my playground. who am i? "
}

export default riddle_obj;